runtime: python27
api_version: 1
threadsafe: true

application: nomaden
version: alpha-002

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
  http_headers:
    Content-Security-Policy: "default-src 'self'; img-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"

- url: /assets
  static_dir: assets
  http_headers:
    Content-Security-Policy: "default-src 'self'; img-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"

- url: /enterpub.html
  static_files: enterpub.html
  upload: enterpub.html
  secure: always
  http_headers:
    Content-Security-Policy: "default-src 'self'; img-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"

- url: /
  script: nomaden.app
  secure: always

- url: /enterPub
  script: nomaden.app
  secure: always

- url: /schedulePubs
  script: nomaden.app
  login: admin
  
- url: /publishMail
  script: nomaden.app
  login: admin

- url: /poster
  script: nomaden.app
  secure: always

- url: /calendar
  script: nomaden.app
  secure: always

- url: /move
  script: nomaden.app
  secure: always
 
- url: /delete
  script: nomaden.app
  login: required
  secure: always
k
- url: /comment
  script: nomaden.app
  secure: always

- url: /archive
  script: nomaden.app
  secure: always

- url: /moderator
  script: nomaden.app
  login: required
  secure: always

- url: /moderatorAdd
  script: nomaden.app
  login: admin
  secure: always

- url: /moderatorDel
  script: nomaden.app
  login: admin
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
