runtime: python27
api_version: 1
threadsafe: true

application: nomaden
version: alpha-002

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /assets
  static_dir: assets

- url: /enterpub.html
  static_files: enterpub.html
  upload: enterpub.html
  secure: always

- url: /
  script: nomaden.app
  secure: always

- url: /enterPub
  script: nomaden.app
  secure: always

- url: /schedulePubs
  script: nomaden.app
  login: admin

- url: /moveForward
  script: nomaden.app
  secure: always

- url: /delete
  script: nomaden.app
  login: required
  secure: always

- url: /comment
  script: nomaden.app
  secure: always

- url: /archive
  script: nomaden.app
  secure: always

- url: /moderator
  script: nomaden.app
  login: required
  secure: always

- url: /moderatorAdd
  script: nomaden.app
  login: admin
  secure: always

- url: /moderatorDel
  script: nomaden.app
  login: admin
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
