runtime: python27
api_version: 1
threadsafe: true

application: nomaden
version: alpha-002

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon.ico
  http_headers:
    Content-Security-Policy: "default-src 'self'; img-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: "nosniff"

- url: /assets
  static_dir: assets
  http_headers:
    Content-Security-Policy: "default-src 'self'; img-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: nosniff

- url: /enterpub.html
  static_files: enterpub.html
  upload: enterpub.html
  secure: always
  http_headers:
    Content-Security-Policy: "default-src 'self'; img-src 'self'; frame-ancestors 'none'"
    Strict-Transport-Security: "max-age=31536000"
    X-Frame-Options: "DENY"
    X-XSS-Protection: "1; mode=block"
    X-Content-Type-Options: nosniff

- url: /.*
  script: nomaden.app
  secure: always
