# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nomads.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nomads.proto',
  package='nomadsapp',
  syntax='proto3',
  serialized_pb=_b('\n\x0cnomads.proto\x12\tnomadsapp\"\x9a\x02\n\x0b\x41ppointment\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06street\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x13\n\x0bpublictrans\x18\x04 \x01(\t\x12\x0e\n\x06source\x18\x05 \x01(\t\x12\x0f\n\x07\x65ntered\x18\x06 \x01(\t\x12\x0f\n\x07setdate\x18\x07 \x01(\t\x12\x11\n\tsortorder\x18\x08 \x01(\x05\x12\x0f\n\x07removed\x18\t \x01(\t\x12\x30\n\x08\x63omments\x18\n \x03(\x0b\x32\x1e.nomadsapp.Appointment.Comment\x12\n\n\x02id\x18\x0b \x01(\t\x1a\x36\n\x07\x43omment\x12\r\n\x05uname\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"6\n\x0e\x41ppoinmentList\x12$\n\x04\x61pps\x18\x01 \x03(\x0b\x32\x16.nomadsapp.Appointmentb\x06proto3')
)




_APPOINTMENT_COMMENT = _descriptor.Descriptor(
  name='Comment',
  full_name='nomadsapp.Appointment.Comment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uname', full_name='nomadsapp.Appointment.Comment.uname', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='text', full_name='nomadsapp.Appointment.Comment.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='nomadsapp.Appointment.Comment.source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=310,
)

_APPOINTMENT = _descriptor.Descriptor(
  name='Appointment',
  full_name='nomadsapp.Appointment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='nomadsapp.Appointment.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='street', full_name='nomadsapp.Appointment.street', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='city', full_name='nomadsapp.Appointment.city', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publictrans', full_name='nomadsapp.Appointment.publictrans', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='source', full_name='nomadsapp.Appointment.source', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entered', full_name='nomadsapp.Appointment.entered', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='setdate', full_name='nomadsapp.Appointment.setdate', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sortorder', full_name='nomadsapp.Appointment.sortorder', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='removed', full_name='nomadsapp.Appointment.removed', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comments', full_name='nomadsapp.Appointment.comments', index=9,
      number=10, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='id', full_name='nomadsapp.Appointment.id', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_APPOINTMENT_COMMENT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=310,
)


_APPOINMENTLIST = _descriptor.Descriptor(
  name='AppoinmentList',
  full_name='nomadsapp.AppoinmentList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='apps', full_name='nomadsapp.AppoinmentList.apps', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=312,
  serialized_end=366,
)

_APPOINTMENT_COMMENT.containing_type = _APPOINTMENT
_APPOINTMENT.fields_by_name['comments'].message_type = _APPOINTMENT_COMMENT
_APPOINMENTLIST.fields_by_name['apps'].message_type = _APPOINTMENT
DESCRIPTOR.message_types_by_name['Appointment'] = _APPOINTMENT
DESCRIPTOR.message_types_by_name['AppoinmentList'] = _APPOINMENTLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Appointment = _reflection.GeneratedProtocolMessageType('Appointment', (_message.Message,), dict(

  Comment = _reflection.GeneratedProtocolMessageType('Comment', (_message.Message,), dict(
    DESCRIPTOR = _APPOINTMENT_COMMENT,
    __module__ = 'nomads_pb2'
    # @@protoc_insertion_point(class_scope:nomadsapp.Appointment.Comment)
    ))
  ,
  DESCRIPTOR = _APPOINTMENT,
  __module__ = 'nomads_pb2'
  # @@protoc_insertion_point(class_scope:nomadsapp.Appointment)
  ))
_sym_db.RegisterMessage(Appointment)
_sym_db.RegisterMessage(Appointment.Comment)

AppoinmentList = _reflection.GeneratedProtocolMessageType('AppoinmentList', (_message.Message,), dict(
  DESCRIPTOR = _APPOINMENTLIST,
  __module__ = 'nomads_pb2'
  # @@protoc_insertion_point(class_scope:nomadsapp.AppoinmentList)
  ))
_sym_db.RegisterMessage(AppoinmentList)


# @@protoc_insertion_point(module_scope)
